"""
Time Series Augmentation for R-JEPA.

Provides composable transforms for financial time series data augmentation.
Only the **context** window is augmented during training — the target window
remains unchanged, preserving the actual future for self-supervised learning.

Typical usage with moderate settings for normalized financial data::

    from data.augmentation import GaussianNoise, MagnitudeWarping, Compose

    augmenter = Compose([
        GaussianNoise(std=0.02),
        MagnitudeWarping(sigma=0.1, knot_count=5),
    ])
    dataset = StockDataset(data, seq_len, pred_hz, augmenter=augmenter)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

import torch
from torch import Tensor
import torch.nn.functional as F


# ── Transform interface ──────────────────────────────────────────────

Transform = Callable[[Tensor], Tensor]
"""A transform takes a context tensor ``[seq_len, n_features]`` and returns
an augmented tensor of the same shape."""


class Compose:
    """Chain multiple transforms together, applied in order.

    Args:
        transforms: List of transform callables.
    """

    def __init__(self, transforms: list[Transform]) -> None:
        self.transforms = transforms

    def __call__(self, x: Tensor) -> Tensor:
        for t in self.transforms:
            x = t(x)
        return x

    def __repr__(self) -> str:
        return f"Compose({self.transforms})"


# ── Concrete transforms ──────────────────────────────────────────────


class GaussianNoise:
    """Add independent Gaussian noise to every element.

    This is the simplest and most robust regularisation for financial data.
    Applied to the context, it forces the encoder to learn noise-invariant
    representations.

    Args:
        std: Standard deviation of the noise. For standardised data
            (zero mean, unit variance), ``std=0.01``–``0.05`` is a
            sensible range.  ``0`` disables the transform.
    """

    def __init__(self, std: float = 0.02) -> None:
        if std < 0:
            raise ValueError(f"std must be >= 0, got {std}")
        self.std = std

    def __call__(self, x: Tensor) -> Tensor:
        if self.std == 0.0:
            return x
        return x + torch.randn_like(x) * self.std

    def __repr__(self) -> str:
        return f"GaussianNoise(std={self.std})"


class MagnitudeWarping:
    """Multiply each feature by a smooth random curve.

    The curve is generated by interpolating between a small number of
    random knots with cubic splines.  This preserves the temporal
    structure of the sequence while distorting the *magnitude* of
    individual time steps — mimicking intraday volatility shifts.

    Args:
        sigma: Standard deviation of the knot perturbations (log-scale).
            ``sigma=0`` disables the transform.  For normalised data,
            ``sigma=0.1``–``0.2`` is a sensible range.
        knot_count: Number of control knots for the spline.
            Fewer knots = smoother, more global distortion.
            Must be >= 2.
    """

    def __init__(self, sigma: float = 0.1, knot_count: int = 5) -> None:
        if sigma < 0:
            raise ValueError(f"sigma must be >= 0, got {sigma}")
        if knot_count < 2:
            raise ValueError(f"knot_count must be >= 2, got {knot_count}")
        self.sigma = sigma
        self.knot_count = knot_count

    def __call__(self, x: Tensor) -> Tensor:
        if self.sigma == 0.0:
            return x

        seq_len, n_features = x.shape
        device = x.device
        dtype = x.dtype

        # Knot positions linearly spaced in [0, 1]
        knots = torch.linspace(0, 1, self.knot_count, device=device, dtype=dtype)

        # Random perturbations at knots (log scale → multiplicative warp)
        perturbations = torch.exp(
            torch.randn(self.knot_count, n_features, device=device, dtype=dtype)
            * self.sigma
        )  # [knot_count, n_features]

        # Original time positions in [0, 1]
        t = torch.linspace(0, 1, seq_len, device=device, dtype=dtype)  # [seq_len]

        # Interpolate perturbations from knot positions to all time steps
        # Use linear interpolation for simplicity and speed; for cubic use
        # cubic_spline_interp but that requires scipy.
        t_flat = t.unsqueeze(-1).expand(seq_len, 1)  # [seq_len, 1]
        knots_flat = knots.unsqueeze(0).expand(1, self.knot_count)  # [1, knots]

        # Find interpolation weights
        dist = (t_flat - knots_flat).abs()  # [seq_len, knots]
        weights = F.softmax(-dist * 100, dim=1)  # near-neighbour weighting

        warp = weights @ perturbations  # [seq_len, n_features]

        return x * warp

    def __repr__(self) -> str:
        return f"MagnitudeWarping(sigma={self.sigma}, knot_count={self.knot_count})"


class TimeWarping:
    """Locally distort the time axis by perturbing cumulative increments.

    This creates sequences with slightly different pacing — some intervals
    are stretched, others compressed — while preserving the overall order.
    Useful for making the predictor robust to varying market rhythms.

    Args:
        sigma: Standard deviation of the per-step perturbation.
            ``sigma=0`` disables the transform.  ``0.1``–``0.3`` is a
            sensible range for normalised data.
    """

    def __init__(self, sigma: float = 0.15) -> None:
        if sigma < 0:
            raise ValueError(f"sigma must be >= 0, got {sigma}")
        self.sigma = sigma

    def __call__(self, x: Tensor) -> Tensor:
        if self.sigma == 0.0:
            return x

        seq_len, n_features = x.shape
        device = x.device
        dtype = x.dtype

        # Generate perturbed cumulative time increments
        increments = torch.exp(
            torch.randn(seq_len, 1, device=device, dtype=dtype) * self.sigma
        )  # [seq_len, 1]
        cumsum = torch.cumsum(increments, dim=0)  # [seq_len, 1]
        # Normalise to [0, 1]
        cumsum = cumsum / cumsum[-1]

        # Original uniform grid
        orig_t = torch.linspace(0, 1, seq_len, device=device, dtype=dtype)  # [seq_len]

        # Interpolate: for each point in the warped grid, find the value
        # from the original grid.  We use `cumsum` as the *source* positions
        # and `orig_t` as the *target* positions, then swap.
        #
        # Actually we want: given warped positions cumsum, what are the
        # feature values?  This is a scatter/gather operation.
        #
        # Simpler approach: for each original index i, we map it to its
        # warped position cumsum[i], then use grid_sample-style interpolation.
        #
        # Most direct: use `torch.interp` (1D) per feature.

        warped = torch.stack([
            self._interp1d(cumsum.squeeze(-1), x[:, f], orig_t)
            for f in range(n_features)
        ], dim=1)  # [seq_len, n_features]

        return warped

    @staticmethod
    def _interp1d(xp: Tensor, fp: Tensor, x: Tensor) -> Tensor:
        """1D linear interpolation equivalent to ``numpy.interp``.

        Args:
            xp: Source positions ``[N]`` (monotonic increasing).
            fp: Source values ``[N]``.
            x: Target positions ``[M]``.

        Returns:
            Interpolated values ``[M]``.
        """
        # Find indices where x would be inserted in xp
        # Using broadcasting to find nearest neighbours
        N = xp.shape[0]
        M = x.shape[0]

        # xp: [N], x: [M] -> diff: [M, N]
        diff = x.unsqueeze(1) - xp.unsqueeze(0)  # [M, N]
        # For each target position, find right neighbour index
        right_idx = (diff < 0).float().argmax(dim=1).clamp(1, N - 1)  # [M]
        left_idx = right_idx - 1  # [M]

        x_left = xp[left_idx]
        x_right = xp[right_idx]
        denom = x_right - x_left
        # Guard against division by zero
        denom = denom.clamp(min=1e-10)

        t_frac = (x - x_left) / denom
        result = fp[left_idx] + t_frac * (fp[right_idx] - fp[left_idx])
        return result

    def __repr__(self) -> str:
        return f"TimeWarping(sigma={self.sigma})"


class WindowSlice:
    """Randomly crop a sub-window of the context and resize back.

    Selects a contiguous sub-sequence from the context, then interpolates
    it back to the original sequence length.  This simulates variability
    in the observation window and encourages the encoder to be robust to
    the exact alignment of the context boundaries.

    Args:
        ratio: Fraction of the sequence to *remove* (crop).
            ``ratio=0`` disables the transform.  ``0.1``–``0.3`` is a
            sensible range (e.g. 0.2 removes 20% of the sequence).
    """

    def __init__(self, ratio: float = 0.15) -> None:
        if not 0 <= ratio < 1:
            raise ValueError(f"ratio must be in [0, 1), got {ratio}")
        self.ratio = ratio

    def __call__(self, x: Tensor) -> Tensor:
        if self.ratio == 0.0:
            return x

        seq_len, n_features = x.shape
        crop_len = int(seq_len * (1 - self.ratio))

        if crop_len < 2:
            return x  # too short to crop meaningfully

        # Random start position for the crop
        max_start = seq_len - crop_len
        start = torch.randint(0, max_start + 1, (1,)).item()

        cropped = x[start:start + crop_len]  # [crop_len, n_features]

        # Resize back to original length via linear interpolation
        # We use interpolate which expects [N, C, L] format
        cropped_3d = cropped.T.unsqueeze(0)  # [1, n_features, crop_len]
        resized = F.interpolate(
            cropped_3d, size=seq_len, mode="linear", align_corners=False,
        )  # [1, n_features, seq_len]
        resized = resized.squeeze(0).T  # [seq_len, n_features]

        return resized

    def __repr__(self) -> str:
        return f"WindowSlice(ratio={self.ratio})"
